/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.aliyuncs.sofa.transform.v20190815;

import com.aliyuncs.sofa.model.v20190815.CreateLinkeantcodeAntcodeNewlabelforgivenrepositorywithgivennameandcolorResponse;
import com.aliyuncs.transform.UnmarshallerContext;


public class CreateLinkeantcodeAntcodeNewlabelforgivenrepositorywithgivennameandcolorResponseUnmarshaller {

	public static CreateLinkeantcodeAntcodeNewlabelforgivenrepositorywithgivennameandcolorResponse unmarshall(CreateLinkeantcodeAntcodeNewlabelforgivenrepositorywithgivennameandcolorResponse createLinkeantcodeAntcodeNewlabelforgivenrepositorywithgivennameandcolorResponse, UnmarshallerContext _ctx) {
		
		createLinkeantcodeAntcodeNewlabelforgivenrepositorywithgivennameandcolorResponse.setRequestId(_ctx.stringValue("CreateLinkeantcodeAntcodeNewlabelforgivenrepositorywithgivennameandcolorResponse.RequestId"));
		createLinkeantcodeAntcodeNewlabelforgivenrepositorywithgivennameandcolorResponse.setResultCode(_ctx.stringValue("CreateLinkeantcodeAntcodeNewlabelforgivenrepositorywithgivennameandcolorResponse.ResultCode"));
		createLinkeantcodeAntcodeNewlabelforgivenrepositorywithgivennameandcolorResponse.setResultMessage(_ctx.stringValue("CreateLinkeantcodeAntcodeNewlabelforgivenrepositorywithgivennameandcolorResponse.ResultMessage"));
		createLinkeantcodeAntcodeNewlabelforgivenrepositorywithgivennameandcolorResponse.setColor(_ctx.stringValue("CreateLinkeantcodeAntcodeNewlabelforgivenrepositorywithgivennameandcolorResponse.Color"));
		createLinkeantcodeAntcodeNewlabelforgivenrepositorywithgivennameandcolorResponse.setCreatedAt(_ctx.stringValue("CreateLinkeantcodeAntcodeNewlabelforgivenrepositorywithgivennameandcolorResponse.CreatedAt"));
		createLinkeantcodeAntcodeNewlabelforgivenrepositorywithgivennameandcolorResponse.setDescription(_ctx.stringValue("CreateLinkeantcodeAntcodeNewlabelforgivenrepositorywithgivennameandcolorResponse.Description"));
		createLinkeantcodeAntcodeNewlabelforgivenrepositorywithgivennameandcolorResponse.setGroupId(_ctx.longValue("CreateLinkeantcodeAntcodeNewlabelforgivenrepositorywithgivennameandcolorResponse.GroupId"));
		createLinkeantcodeAntcodeNewlabelforgivenrepositorywithgivennameandcolorResponse.setId(_ctx.longValue("CreateLinkeantcodeAntcodeNewlabelforgivenrepositorywithgivennameandcolorResponse.Id"));
		createLinkeantcodeAntcodeNewlabelforgivenrepositorywithgivennameandcolorResponse.setName(_ctx.stringValue("CreateLinkeantcodeAntcodeNewlabelforgivenrepositorywithgivennameandcolorResponse.Name"));
		createLinkeantcodeAntcodeNewlabelforgivenrepositorywithgivennameandcolorResponse.setProjectId(_ctx.longValue("CreateLinkeantcodeAntcodeNewlabelforgivenrepositorywithgivennameandcolorResponse.ProjectId"));
		createLinkeantcodeAntcodeNewlabelforgivenrepositorywithgivennameandcolorResponse.setResponseStatusCode(_ctx.longValue("CreateLinkeantcodeAntcodeNewlabelforgivenrepositorywithgivennameandcolorResponse.ResponseStatusCode"));
		createLinkeantcodeAntcodeNewlabelforgivenrepositorywithgivennameandcolorResponse.setSourceType(_ctx.stringValue("CreateLinkeantcodeAntcodeNewlabelforgivenrepositorywithgivennameandcolorResponse.SourceType"));
		createLinkeantcodeAntcodeNewlabelforgivenrepositorywithgivennameandcolorResponse.setTemplate(_ctx.booleanValue("CreateLinkeantcodeAntcodeNewlabelforgivenrepositorywithgivennameandcolorResponse.Template"));
		createLinkeantcodeAntcodeNewlabelforgivenrepositorywithgivennameandcolorResponse.setTenantId(_ctx.longValue("CreateLinkeantcodeAntcodeNewlabelforgivenrepositorywithgivennameandcolorResponse.TenantId"));
		createLinkeantcodeAntcodeNewlabelforgivenrepositorywithgivennameandcolorResponse.setUpdatedAt(_ctx.stringValue("CreateLinkeantcodeAntcodeNewlabelforgivenrepositorywithgivennameandcolorResponse.UpdatedAt"));
	 
	 	return createLinkeantcodeAntcodeNewlabelforgivenrepositorywithgivennameandcolorResponse;
	}
}