/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.aliyuncs.sofa.transform.v20190815;

import com.aliyuncs.sofa.model.v20190815.DisableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse;
import com.aliyuncs.transform.UnmarshallerContext;


public class DisableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponseUnmarshaller {

	public static DisableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse unmarshall(DisableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse disableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse, UnmarshallerContext _ctx) {
		
		disableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.setRequestId(_ctx.stringValue("DisableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.RequestId"));
		disableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.setResultCode(_ctx.stringValue("DisableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.ResultCode"));
		disableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.setResultMessage(_ctx.stringValue("DisableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.ResultMessage"));
		disableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.setAccessLevel(_ctx.stringValue("DisableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.AccessLevel"));
		disableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.setAccessUserId(_ctx.longValue("DisableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.AccessUserId"));
		disableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.setAutoCheckSuite(_ctx.booleanValue("DisableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.AutoCheckSuite"));
		disableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.setAvatarUrl(_ctx.stringValue("DisableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.AvatarUrl"));
		disableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.setBuildEvent(_ctx.booleanValue("DisableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.BuildEvent"));
		disableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.setCallUrl(_ctx.stringValue("DisableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.CallUrl"));
		disableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.setChecks(_ctx.booleanValue("DisableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.Checks"));
		disableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.setChecksDependOn(_ctx.stringValue("DisableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.ChecksDependOn"));
		disableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.setCheckResultUrl(_ctx.stringValue("DisableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.CheckResultUrl"));
		disableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.setCheckSite(_ctx.longValue("DisableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.CheckSite"));
		disableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.setCreatedAt(_ctx.stringValue("DisableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.CreatedAt"));
		disableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.setDescription(_ctx.stringValue("DisableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.Description"));
		disableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.setHomepage(_ctx.stringValue("DisableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.Homepage"));
		disableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.setId(_ctx.longValue("DisableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.Id"));
		disableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.setIssueEvent(_ctx.booleanValue("DisableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.IssueEvent"));
		disableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.setMergeRequestEvent(_ctx.booleanValue("DisableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.MergeRequestEvent"));
		disableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.setName(_ctx.stringValue("DisableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.Name"));
		disableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.setNoteEvent(_ctx.booleanValue("DisableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.NoteEvent"));
		disableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.setProperties(_ctx.stringValue("DisableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.Properties"));
		disableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.setPushEvent(_ctx.booleanValue("DisableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.PushEvent"));
		disableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.setResponseStatusCode(_ctx.longValue("DisableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.ResponseStatusCode"));
		disableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.setSourceId(_ctx.longValue("DisableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.SourceId"));
		disableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.setSourceType(_ctx.stringValue("DisableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.SourceType"));
		disableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.setTagPushEvent(_ctx.booleanValue("DisableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.TagPushEvent"));
		disableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.setUpdatedAt(_ctx.stringValue("DisableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.UpdatedAt"));
		disableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.setVisibilityLevel(_ctx.stringValue("DisableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse.VisibilityLevel"));
	 
	 	return disableLinkeantcodeAntcodeGroupsidinstallationsserviceidResponse;
	}
}