/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.aliyuncs.sofa.transform.v20190815;

import com.aliyuncs.sofa.model.v20190815.DisableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse;
import com.aliyuncs.transform.UnmarshallerContext;


public class DisableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponseUnmarshaller {

	public static DisableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse unmarshall(DisableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse disableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse, UnmarshallerContext _ctx) {
		
		disableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.setRequestId(_ctx.stringValue("DisableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.RequestId"));
		disableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.setResultCode(_ctx.stringValue("DisableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.ResultCode"));
		disableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.setResultMessage(_ctx.stringValue("DisableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.ResultMessage"));
		disableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.setAccessLevel(_ctx.stringValue("DisableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.AccessLevel"));
		disableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.setAccessUserId(_ctx.longValue("DisableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.AccessUserId"));
		disableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.setAutoCheckSuite(_ctx.booleanValue("DisableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.AutoCheckSuite"));
		disableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.setAvatarUrl(_ctx.stringValue("DisableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.AvatarUrl"));
		disableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.setBuildEvent(_ctx.booleanValue("DisableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.BuildEvent"));
		disableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.setCallUrl(_ctx.stringValue("DisableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.CallUrl"));
		disableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.setChecks(_ctx.booleanValue("DisableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.Checks"));
		disableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.setChecksDependOn(_ctx.stringValue("DisableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.ChecksDependOn"));
		disableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.setCheckResultUrl(_ctx.stringValue("DisableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.CheckResultUrl"));
		disableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.setCheckSite(_ctx.longValue("DisableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.CheckSite"));
		disableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.setCreatedAt(_ctx.stringValue("DisableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.CreatedAt"));
		disableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.setDescription(_ctx.stringValue("DisableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.Description"));
		disableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.setHomepage(_ctx.stringValue("DisableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.Homepage"));
		disableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.setId(_ctx.longValue("DisableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.Id"));
		disableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.setIssueEvent(_ctx.booleanValue("DisableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.IssueEvent"));
		disableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.setMergeRequestEvent(_ctx.booleanValue("DisableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.MergeRequestEvent"));
		disableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.setName(_ctx.stringValue("DisableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.Name"));
		disableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.setNoteEvent(_ctx.booleanValue("DisableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.NoteEvent"));
		disableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.setProperties(_ctx.stringValue("DisableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.Properties"));
		disableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.setPushEvent(_ctx.booleanValue("DisableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.PushEvent"));
		disableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.setResponseStatusCode(_ctx.longValue("DisableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.ResponseStatusCode"));
		disableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.setSourceId(_ctx.longValue("DisableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.SourceId"));
		disableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.setSourceType(_ctx.stringValue("DisableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.SourceType"));
		disableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.setTagPushEvent(_ctx.booleanValue("DisableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.TagPushEvent"));
		disableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.setUpdatedAt(_ctx.stringValue("DisableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.UpdatedAt"));
		disableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.setVisibilityLevel(_ctx.stringValue("DisableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse.VisibilityLevel"));
	 
	 	return disableLinkeantcodeAntcodeNamespacesidinstallationsserviceidResponse;
	}
}