/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.aliyuncs.sofa.transform.v20190815;

import com.aliyuncs.sofa.model.v20190815.QueryLinkeantcodeAntcodeUpdatesnexistinglabelwithnewnameornowcolorResponse;
import com.aliyuncs.transform.UnmarshallerContext;


public class QueryLinkeantcodeAntcodeUpdatesnexistinglabelwithnewnameornowcolorResponseUnmarshaller {

	public static QueryLinkeantcodeAntcodeUpdatesnexistinglabelwithnewnameornowcolorResponse unmarshall(QueryLinkeantcodeAntcodeUpdatesnexistinglabelwithnewnameornowcolorResponse queryLinkeantcodeAntcodeUpdatesnexistinglabelwithnewnameornowcolorResponse, UnmarshallerContext _ctx) {
		
		queryLinkeantcodeAntcodeUpdatesnexistinglabelwithnewnameornowcolorResponse.setRequestId(_ctx.stringValue("QueryLinkeantcodeAntcodeUpdatesnexistinglabelwithnewnameornowcolorResponse.RequestId"));
		queryLinkeantcodeAntcodeUpdatesnexistinglabelwithnewnameornowcolorResponse.setResultCode(_ctx.stringValue("QueryLinkeantcodeAntcodeUpdatesnexistinglabelwithnewnameornowcolorResponse.ResultCode"));
		queryLinkeantcodeAntcodeUpdatesnexistinglabelwithnewnameornowcolorResponse.setResultMessage(_ctx.stringValue("QueryLinkeantcodeAntcodeUpdatesnexistinglabelwithnewnameornowcolorResponse.ResultMessage"));
		queryLinkeantcodeAntcodeUpdatesnexistinglabelwithnewnameornowcolorResponse.setColor(_ctx.stringValue("QueryLinkeantcodeAntcodeUpdatesnexistinglabelwithnewnameornowcolorResponse.Color"));
		queryLinkeantcodeAntcodeUpdatesnexistinglabelwithnewnameornowcolorResponse.setCreatedAt(_ctx.stringValue("QueryLinkeantcodeAntcodeUpdatesnexistinglabelwithnewnameornowcolorResponse.CreatedAt"));
		queryLinkeantcodeAntcodeUpdatesnexistinglabelwithnewnameornowcolorResponse.setDescription(_ctx.stringValue("QueryLinkeantcodeAntcodeUpdatesnexistinglabelwithnewnameornowcolorResponse.Description"));
		queryLinkeantcodeAntcodeUpdatesnexistinglabelwithnewnameornowcolorResponse.setGroupId(_ctx.longValue("QueryLinkeantcodeAntcodeUpdatesnexistinglabelwithnewnameornowcolorResponse.GroupId"));
		queryLinkeantcodeAntcodeUpdatesnexistinglabelwithnewnameornowcolorResponse.setId(_ctx.longValue("QueryLinkeantcodeAntcodeUpdatesnexistinglabelwithnewnameornowcolorResponse.Id"));
		queryLinkeantcodeAntcodeUpdatesnexistinglabelwithnewnameornowcolorResponse.setName(_ctx.stringValue("QueryLinkeantcodeAntcodeUpdatesnexistinglabelwithnewnameornowcolorResponse.Name"));
		queryLinkeantcodeAntcodeUpdatesnexistinglabelwithnewnameornowcolorResponse.setProjectId(_ctx.longValue("QueryLinkeantcodeAntcodeUpdatesnexistinglabelwithnewnameornowcolorResponse.ProjectId"));
		queryLinkeantcodeAntcodeUpdatesnexistinglabelwithnewnameornowcolorResponse.setResponseStatusCode(_ctx.longValue("QueryLinkeantcodeAntcodeUpdatesnexistinglabelwithnewnameornowcolorResponse.ResponseStatusCode"));
		queryLinkeantcodeAntcodeUpdatesnexistinglabelwithnewnameornowcolorResponse.setSourceType(_ctx.stringValue("QueryLinkeantcodeAntcodeUpdatesnexistinglabelwithnewnameornowcolorResponse.SourceType"));
		queryLinkeantcodeAntcodeUpdatesnexistinglabelwithnewnameornowcolorResponse.setTemplate(_ctx.booleanValue("QueryLinkeantcodeAntcodeUpdatesnexistinglabelwithnewnameornowcolorResponse.Template"));
		queryLinkeantcodeAntcodeUpdatesnexistinglabelwithnewnameornowcolorResponse.setTenantId(_ctx.longValue("QueryLinkeantcodeAntcodeUpdatesnexistinglabelwithnewnameornowcolorResponse.TenantId"));
		queryLinkeantcodeAntcodeUpdatesnexistinglabelwithnewnameornowcolorResponse.setUpdatedAt(_ctx.stringValue("QueryLinkeantcodeAntcodeUpdatesnexistinglabelwithnewnameornowcolorResponse.UpdatedAt"));
	 
	 	return queryLinkeantcodeAntcodeUpdatesnexistinglabelwithnewnameornowcolorResponse;
	}
}