/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.aliyuncs.sofa.transform.v20190815;

import com.aliyuncs.sofa.model.v20190815.QueryLinkeantcodeAntcodeProjectsidpullrequestspullrequestidunsubscribeResponse;
import com.aliyuncs.transform.UnmarshallerContext;


public class QueryLinkeantcodeAntcodeProjectsidpullrequestspullrequestidunsubscribeResponseUnmarshaller {

	public static QueryLinkeantcodeAntcodeProjectsidpullrequestspullrequestidunsubscribeResponse unmarshall(QueryLinkeantcodeAntcodeProjectsidpullrequestspullrequestidunsubscribeResponse queryLinkeantcodeAntcodeProjectsidpullrequestspullrequestidunsubscribeResponse, UnmarshallerContext _ctx) {
		
		queryLinkeantcodeAntcodeProjectsidpullrequestspullrequestidunsubscribeResponse.setRequestId(_ctx.stringValue("QueryLinkeantcodeAntcodeProjectsidpullrequestspullrequestidunsubscribeResponse.RequestId"));
		queryLinkeantcodeAntcodeProjectsidpullrequestspullrequestidunsubscribeResponse.setResultCode(_ctx.stringValue("QueryLinkeantcodeAntcodeProjectsidpullrequestspullrequestidunsubscribeResponse.ResultCode"));
		queryLinkeantcodeAntcodeProjectsidpullrequestspullrequestidunsubscribeResponse.setResultMessage(_ctx.stringValue("QueryLinkeantcodeAntcodeProjectsidpullrequestspullrequestidunsubscribeResponse.ResultMessage"));
		queryLinkeantcodeAntcodeProjectsidpullrequestspullrequestidunsubscribeResponse.setCreatedAt(_ctx.stringValue("QueryLinkeantcodeAntcodeProjectsidpullrequestspullrequestidunsubscribeResponse.CreatedAt"));
		queryLinkeantcodeAntcodeProjectsidpullrequestspullrequestidunsubscribeResponse.setEmail(_ctx.stringValue("QueryLinkeantcodeAntcodeProjectsidpullrequestspullrequestidunsubscribeResponse.Email"));
		queryLinkeantcodeAntcodeProjectsidpullrequestspullrequestidunsubscribeResponse.setId(_ctx.longValue("QueryLinkeantcodeAntcodeProjectsidpullrequestspullrequestidunsubscribeResponse.Id"));
		queryLinkeantcodeAntcodeProjectsidpullrequestspullrequestidunsubscribeResponse.setResponseStatusCode(_ctx.longValue("QueryLinkeantcodeAntcodeProjectsidpullrequestspullrequestidunsubscribeResponse.ResponseStatusCode"));
		queryLinkeantcodeAntcodeProjectsidpullrequestspullrequestidunsubscribeResponse.setSubscribableId(_ctx.longValue("QueryLinkeantcodeAntcodeProjectsidpullrequestspullrequestidunsubscribeResponse.SubscribableId"));
		queryLinkeantcodeAntcodeProjectsidpullrequestspullrequestidunsubscribeResponse.setSubscribableType(_ctx.stringValue("QueryLinkeantcodeAntcodeProjectsidpullrequestspullrequestidunsubscribeResponse.SubscribableType"));
		queryLinkeantcodeAntcodeProjectsidpullrequestspullrequestidunsubscribeResponse.setSubscribed(_ctx.booleanValue("QueryLinkeantcodeAntcodeProjectsidpullrequestspullrequestidunsubscribeResponse.Subscribed"));
		queryLinkeantcodeAntcodeProjectsidpullrequestspullrequestidunsubscribeResponse.setUpdatedAt(_ctx.stringValue("QueryLinkeantcodeAntcodeProjectsidpullrequestspullrequestidunsubscribeResponse.UpdatedAt"));
		queryLinkeantcodeAntcodeProjectsidpullrequestspullrequestidunsubscribeResponse.setUserId(_ctx.longValue("QueryLinkeantcodeAntcodeProjectsidpullrequestspullrequestidunsubscribeResponse.UserId"));
	 
	 	return queryLinkeantcodeAntcodeProjectsidpullrequestspullrequestidunsubscribeResponse;
	}
}