/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.aliyuncs.sofa.transform.v20190815;

import com.aliyuncs.sofa.model.v20190815.QueryLinkeantcodeAntcodeProjectsupdateprojectpullrequestconfigResponse;
import com.aliyuncs.transform.UnmarshallerContext;


public class QueryLinkeantcodeAntcodeProjectsupdateprojectpullrequestconfigResponseUnmarshaller {

	public static QueryLinkeantcodeAntcodeProjectsupdateprojectpullrequestconfigResponse unmarshall(QueryLinkeantcodeAntcodeProjectsupdateprojectpullrequestconfigResponse queryLinkeantcodeAntcodeProjectsupdateprojectpullrequestconfigResponse, UnmarshallerContext _ctx) {
		
		queryLinkeantcodeAntcodeProjectsupdateprojectpullrequestconfigResponse.setRequestId(_ctx.stringValue("QueryLinkeantcodeAntcodeProjectsupdateprojectpullrequestconfigResponse.RequestId"));
		queryLinkeantcodeAntcodeProjectsupdateprojectpullrequestconfigResponse.setResultCode(_ctx.stringValue("QueryLinkeantcodeAntcodeProjectsupdateprojectpullrequestconfigResponse.ResultCode"));
		queryLinkeantcodeAntcodeProjectsupdateprojectpullrequestconfigResponse.setResultMessage(_ctx.stringValue("QueryLinkeantcodeAntcodeProjectsupdateprojectpullrequestconfigResponse.ResultMessage"));
		queryLinkeantcodeAntcodeProjectsupdateprojectpullrequestconfigResponse.setCreatedAt(_ctx.stringValue("QueryLinkeantcodeAntcodeProjectsupdateprojectpullrequestconfigResponse.CreatedAt"));
		queryLinkeantcodeAntcodeProjectsupdateprojectpullrequestconfigResponse.setFfOnlyEnabled(_ctx.booleanValue("QueryLinkeantcodeAntcodeProjectsupdateprojectpullrequestconfigResponse.FfOnlyEnabled"));
		queryLinkeantcodeAntcodeProjectsupdateprojectpullrequestconfigResponse.setId(_ctx.longValue("QueryLinkeantcodeAntcodeProjectsupdateprojectpullrequestconfigResponse.Id"));
		queryLinkeantcodeAntcodeProjectsupdateprojectpullrequestconfigResponse.setOnlyAllChecksSucceed(_ctx.booleanValue("QueryLinkeantcodeAntcodeProjectsupdateprojectpullrequestconfigResponse.OnlyAllChecksSucceed"));
		queryLinkeantcodeAntcodeProjectsupdateprojectpullrequestconfigResponse.setOnlyAllDiscussionsResolved(_ctx.booleanValue("QueryLinkeantcodeAntcodeProjectsupdateprojectpullrequestconfigResponse.OnlyAllDiscussionsResolved"));
		queryLinkeantcodeAntcodeProjectsupdateprojectpullrequestconfigResponse.setProjectId(_ctx.longValue("QueryLinkeantcodeAntcodeProjectsupdateprojectpullrequestconfigResponse.ProjectId"));
		queryLinkeantcodeAntcodeProjectsupdateprojectpullrequestconfigResponse.setRebaseEnabled(_ctx.booleanValue("QueryLinkeantcodeAntcodeProjectsupdateprojectpullrequestconfigResponse.RebaseEnabled"));
		queryLinkeantcodeAntcodeProjectsupdateprojectpullrequestconfigResponse.setResponseStatusCode(_ctx.longValue("QueryLinkeantcodeAntcodeProjectsupdateprojectpullrequestconfigResponse.ResponseStatusCode"));
		queryLinkeantcodeAntcodeProjectsupdateprojectpullrequestconfigResponse.setReviewRequired(_ctx.booleanValue("QueryLinkeantcodeAntcodeProjectsupdateprojectpullrequestconfigResponse.ReviewRequired"));
		queryLinkeantcodeAntcodeProjectsupdateprojectpullrequestconfigResponse.setShouldRemoveSourceBranch(_ctx.booleanValue("QueryLinkeantcodeAntcodeProjectsupdateprojectpullrequestconfigResponse.ShouldRemoveSourceBranch"));
		queryLinkeantcodeAntcodeProjectsupdateprojectpullrequestconfigResponse.setSquashMerge(_ctx.booleanValue("QueryLinkeantcodeAntcodeProjectsupdateprojectpullrequestconfigResponse.SquashMerge"));
		queryLinkeantcodeAntcodeProjectsupdateprojectpullrequestconfigResponse.setUpdatedAt(_ctx.stringValue("QueryLinkeantcodeAntcodeProjectsupdateprojectpullrequestconfigResponse.UpdatedAt"));
	 
	 	return queryLinkeantcodeAntcodeProjectsupdateprojectpullrequestconfigResponse;
	}
}